version: '3.9'

services:
  kafka-connect:
    image: confluentinc/cp-kafka-connect:6.2.0
    environment:
      TZ: America/Guayaquil
      CONNECT_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:29092,kafka3:39092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_REST_PORT: '8082'
      CONNECT_GROUP_ID: kafka-connect-sandbox
      CONNECT_PLUGIN_PATH: /usr/local/share/kafka/plugins
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-sandbox-config
      CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-sandbox-offsets
      CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-sandbox-status
    ports:
      - 8082:8082
    restart: on-failure
    volumes:
      - ./plugins:/usr/local/share/kafka/plugins:rw

  mongo:
    image: mongo:5
    environment:
      TZ: America/Guayaquil
      MONGO_INITDB_ROOT_PASSWORD: notasecret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - mongo_data:/data/db:rw

  mongo-express:
    image: mongo-express:0.54
    environment:
      TZ: America/Guayaquil
      ME_CONFIG_MONGODB_ADMINPASSWORD: notasecret
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 7070:8081
    restart: on-failure

  mysql:
    image: mysql:8
    environment:
      TZ: America/Guayaquil
      MYSQL_DATABASE: sandbox
      MYSQL_ROOT_PASSWORD: notasecret
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql:rw

  postgres:
    image: postgres:13
    environment:
      TZ: America/Guayaquil
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: notasecret
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:4
    environment:
      TZ: America/Guayaquil
    ports:
      - 9090:8080
    restart: on-failure

volumes:
  mongo_data:
  mysql_data:
  postgres_data:

networks:
  default:
    external: true
    name: kafka-sandbox_network
