version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    environment:
      TZ: America/Guayaquil
    ports:
      - 9000:9000
      - 8000:8000
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
      - portainer_data:/data:rw

volumes:
  portainer_data: