server:
  port: 8585

management:
  endpoints:
    web:
      exposure:
        include: mappings, health

spring:
  kafka:
    topic: kafka-spring-boot.customers
    consumer:
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      group-id: kafka-spring-boot.consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "kafka.sandbox.domain"
    producer:
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
