version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      TZ: America/Guayaquil
      MYSQL_DATABASE: sandbox
      MYSQL_ROOT_PASSWORD: notasecret
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:13
    environment:
      TZ: America/Guayaquil
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: notasecret
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    environment:
      TZ: America/Guayaquil
    ports:
      - 9090:8080
    restart: on-failure

volumes:
  mysql_data:
  postgres_data:

networks:
  default:
    external: true
    name: kafka-sandbox_network
