version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      - TZ=America/Guayaquil
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
    ports:
      - 2181:2181
    networks:
      - kafka_network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_datalog:/var/lib/zookeeper/log
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:6.1.0
    environment:
      - TZ=America/Guayaquil
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9093:9093
    networks:
      - kafka_network
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: on-failure

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:

networks:
  kafka_network:
