version: "3.9"

services:
  kafka-rest:
    image: confluentinc/cp-kafka-rest:${VERSION}
    environment:
      TZ: America/Guayaquil
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    ports:
      - 8082:8082
    restart: on-failure
    healthcheck:
      test: curl http://localhost:8082
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  default:
    external: true
    name: kafka-sandbox_network
