version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    environment:
      TZ: America/Guayaquil
    ports:
      - 1883:1883
    restart: on-failure
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data

volumes:
  mosquitto_data:

networks:
  default:
    external: true
    name: kafka-sandbox_network
