version: "3.9"

services:
  kafka1:
    image: confluentinc/cp-kafka:6.1.0
    environment:
      - TZ=America/Guayaquil
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:12181,zookeeper2:22181,zookeeper3:32181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:19093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka1:19092,EXTERNAL://localhost:19093
      - KAFKA_BROKER_ID=1
    ports:
      - 19093:19093
    volumes:
      - kafka1_data:/var/lib/kafka/data
    restart: on-failure

  kafka2:
    image: confluentinc/cp-kafka:6.1.0
    environment:
      - TZ=America/Guayaquil
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:12181,zookeeper2:22181,zookeeper3:32181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:29093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka2:29092,EXTERNAL://localhost:29093
      - KAFKA_BROKER_ID=2
    ports:
      - 29093:29093
    volumes:
      - kafka2_data:/var/lib/kafka/data
    restart: on-failure

  kafka3:
    image: confluentinc/cp-kafka:6.1.0
    environment:
      - TZ=America/Guayaquil
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:12181,zookeeper2:22181,zookeeper3:32181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:39092,EXTERNAL://0.0.0.0:39093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka3:39092,EXTERNAL://localhost:39093
      - KAFKA_BROKER_ID=3
    ports:
      - 39093:39093
    volumes:
      - kafka3_data:/var/lib/kafka/data
    restart: on-failure

  zookeeper1:
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      - TZ=America/Guayaquil
      - ZOOKEEPER_CLIENT_PORT=12181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    ports:
      - 12181:12181
    volumes:
      - zookeeper1_data:/var/lib/zookeeper/data
      - zookeeper1_datalog:/var/lib/zookeeper/log
    restart: on-failure

  zookeeper2:
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      - TZ=America/Guayaquil
      - ZOOKEEPER_CLIENT_PORT=22181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    ports:
      - 22181:22181
    volumes:
      - zookeeper2_data:/var/lib/zookeeper/data
      - zookeeper2_datalog:/var/lib/zookeeper/log
    restart: on-failure

  zookeeper3:
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      - TZ=America/Guayaquil
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    ports:
      - 32181:32181
    volumes:
      - zookeeper3_data:/var/lib/zookeeper/data
      - zookeeper3_datalog:/var/lib/zookeeper/log
    restart: on-failure

volumes:
  zookeeper1_data:
  zookeeper1_datalog:
  zookeeper2_data:
  zookeeper2_datalog:
  zookeeper3_data:
  zookeeper3_datalog:
  kafka1_data:
  kafka2_data:
  kafka3_data:

networks:
  default:
    external: true
    name: kafka-sandbox_network