version: '3.9'

services:
  mongo:
    image: mongo:5
    environment:
      TZ: America/Guayaquil
      MONGO_INITDB_ROOT_PASSWORD: notasecret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - mongo_data:/data/db:rw

  mongo-express:
    image: mongo-express:0.54
    environment:
      TZ: America/Guayaquil
      ME_CONFIG_MONGODB_ADMINPASSWORD: notasecret
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 7070:8081
    restart: on-failure

volumes:
  mongo_data:

networks:
  default:
    external: true
    name: kafka-sandbox_network
