version: "3.9"

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:${VERSION}
    environment:
      TZ: America/Guayaquil
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      SCHEMA_REGISTRY_DEBUG: "true"
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: kafka-schema-registry.schemas
    ports:
      - 8081:8081
    restart: on-failure
    healthcheck:
      test: curl http://localhost:8081
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  default:
    external: true
    name: kafka-sandbox_network
