version: '3.9'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    environment:
      TZ: America/Guayaquil
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_DEBUG: 'true'
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092,PLAINTEXT://kafka2:29092,PLAINTEXT://kafka3:39092
    ports:
      - 8081:8081
    restart: on-failure

networks:
  default:
    external: true
    name: kafka-sandbox_network
